name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: rustup update
      - name: Build
        run: cargo build --verbose
